# metadata/metadata_models.py
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional

@dataclass
class CommercialIntent:
    primary_industry: str = ""
    target_audience: str = ""
    concept_tags: List[str] = field(default_factory=list)
    confidence: float = 0.0

@dataclass
class MetadataQualityScore:
    overall_score: float = 0.0
    seo_quality: float = 0.0
    commercial_quality: float = 0.0
    readability: float = 0.0
    completeness: float = 0.0

@dataclass
class MetadataConfidence:
    overall_confidence: float = 0.0
    title_confidence: float = 0.0
    description_confidence: float = 0.0
    keywords_confidence: float = 0.0
    category_confidence: float = 0.0

@dataclass
class GeneratedMetadata:
    """Core domain model representing structured stock metadata generated by AI pipelines."""
    id: str
    image_hash: str
    title: str = ""
    description: str = ""
    keywords: List[str] = field(default_factory=list)
    
    primary_category: str = ""
    secondary_category: str = ""
    
    detected_objects: List[str] = field(default_factory=list)
    detected_scene: str = ""
    
    commercial_intent: CommercialIntent = field(default_factory=CommercialIntent)
    quality_score: MetadataQualityScore = field(default_factory=MetadataQualityScore)
    confidence_score: MetadataConfidence = field(default_factory=MetadataConfidence)
    
    marketplace: str = "generic"
    language: str = "en"
    
    provider: str = "unknown"
    model: str = "unknown"
    prompt_version: str = "unknown"
    
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)